const CATALOG=[
    {
        id:'cosmetic-bags-element1',
        name:'Пілінг-скатка LAIKOU з екстрактом ромашки ',
        img:'https://github.com/RusikOkrenets/glorymix-catalog-foto/blob/main/LAikou%20gel.jpg?raw=true',
        number:'120г',
        price:'105.00',
        category:'care-face',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
        
    },
    {
        id:'cosmetic-bags-element2',
        name:'Скраб MEOW DEMON з екстрактом лимона',
        img:'https://github.com/RusikOkrenets/glorymix-catalog-foto/blob/main/MEOW%20DEMON.jpg?raw=true',
        number:'120г',
        price:'105.00',        
        category:'care-face',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, 
    {
        id:'cosmetic-bags-element3',
        name:'Скраб-скатка BIOAQUA, з екстрактом рису',
        img:'https://github.com/RusikOkrenets/glorymix-catalog-foto/blob/main/bioaqua-exfoliating-gel.jpg?raw=true',
        number:'140г',
        price:'105.00',
        category:'care-face',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, {
        id:'cosmetic-bags-element4',
        name:'Пінка-мус для вмивання Rorec Aloe Vera',
        img:'https://github.com/RusikOkrenets/glorymix-catalog-foto/blob/main/Rorec%20Aloe.jpg?raw=true',
        number:'120 мл',
        price:'145.00',
        category:'care-face',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, {
        id:'cosmetic-bags-element5',
        name:'Щітка зубна Wanmao',
        img:'https://github.com/RusikOkrenets/glorymix-catalog-foto/blob/main/wanmao.jpg?raw=true',
        number:'1шт',
        price:'65.00',
        category:'care-face',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, {
        id:'cosmetic-bags-element6',
        name:'Щітка для вмивання обличчя силіконова "Восьминіг"',
        img:'https://github.com/RusikOkrenets/glorymix-catalog-foto/blob/main/photo_2020-08-03_13-50-05%20(2)-600x600.jpg?raw=true',
        number:'1шт',
        price:'50.00',
        category:'care-cosmetic-bags',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, 
    {
        id:'cosmetic-bags-element7',
        name:'Щітка для очищення носа від чорних точок',
        img:'https://raw.githubusercontent.com/RusikOkrenets/glorymix-catalog-foto/881299151bd2e6aeb47c005b5574dc23d5ddcfac/black.jpg',
        number:'1шт',
        price:'45.00',
        category:'care-cosmetic-bags',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, {
        id:'cosmetic-bags-element8',
        name:'Масло масажне Disaar Coconut Oil',
        img:'https://raw.githubusercontent.com/RusikOkrenets/glorymix-catalog-foto/d5088d1e487dca9a01a0adb096d4383121d3b4c9/disaar.jpg',
        number:'1шт',
        price:'185.00',
        category:'care-cosmetic-bags',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    }, {
        id:'cosmetic-bags-element9',
        name:'Cкраб Skin Beautiful Bath Salts Blueberry',
        img:'https://raw.githubusercontent.com/RusikOkrenets/glorymix-catalog-foto/f3d54db1ba0a8fd979cdee3fbdb0f4f92ef3aacb/Bath%20Salts%20Blueberry.jpg',
        number:'1шт',
        price:'135.00',
        category:'care-cosmetic-bags',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    },
    {
        id:'cosmetic-bags-element10',
        name:'Скраб кавовий Moolinse',
        img:'https://raw.githubusercontent.com/RusikOkrenets/glorymix-catalog-foto/da38651f99547e890e6a00b2dcb33321ee3ccea0/Moolinse.jpg',
        number:'1шт',
        price:'135.00',
        category:'care-cosmetic-bags',
        description:'Тут буде опис товару, теееееееееееееееееееееекст',
    },


];